# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CouchCoach' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for CouchCoach
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  
  # malia added these and hopes they work from personal accnt
  pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
  pod 'Google/SignIn', '~> 3.0.3'
end
 
